# Generated by Django 3.0.5 on 2020-05-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Acción',
                'verbose_name_plural': 'acciones',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='iPhone 7, Samsung S8, Chrome, Chrome Mac, Mozilla, Safari', max_length=255, verbose_name='Nombre')),
                ('so_version', models.CharField(blank=True, help_text='iOS 12.4.1, Android 9.', max_length=255, null=True, verbose_name='Versión Sistema Operativo (si aplica)')),
            ],
        ),
    ]
